"""Add queue_jobs table.

Revision ID: e5e3e3a7c63a
Revises: cf3b3f99916b
Create Date: 2026-03-05 22:27:06.780394+00:00
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5e3e3a7c63a"
down_revision: str | None = "cf3b3f99916b"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("backend_job_id", sa.String(length=256), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(length=128), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("build_id", sa.Integer(), nullable=True),
        sa.Column(
            "progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_completed", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "idx_queue_jobs_kind", "queue_jobs", ["kind"], unique=False
    )
    op.create_index(
        "idx_queue_jobs_org_id", "queue_jobs", ["org_id"], unique=False
    )
    op.create_index(
        "idx_queue_jobs_status", "queue_jobs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_queue_jobs_status", table_name="queue_jobs")
    op.drop_index("idx_queue_jobs_org_id", table_name="queue_jobs")
    op.drop_index("idx_queue_jobs_kind", table_name="queue_jobs")
    op.drop_table("queue_jobs")
    # ### end Alembic commands ###
