"""Add organization table.

Revision ID: cf3b3f99916b
Revises:
Create Date: 2026-02-25 22:33:05.145751+00:00
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf3b3f99916b"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("base_domain", sa.String(length=256), nullable=False),
        sa.Column(
            "url_scheme",
            sa.Enum(
                "subdomain",
                "path_prefix",
                name="urlscheme",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("root_path_prefix", sa.Text(), nullable=False),
        sa.Column(
            "slug_rewrite_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "lifecycle_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("purgatory_retention_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "idx_organizations_slug", "organizations", ["slug"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_organizations_slug", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
